# Database configuration
mysql:
  type: "sqlite"
  host: "localhost"
  port: 3306
  username: "root"
  password: "example"
  database: "phone"
  ssl: false 100

# Plugin configuration
resourcepack:
  enabled: true
  url: "https://github.com/Michelo11/Phone/releases/download/v1.0/Custom.Phone.zip"

repeater-distance: 30

messages:
  commands:
    player-only: "&8» &cOnly players can use this command"

    no-permission: "&8» &cYou don't have permission to use this command"
    player-not-found: "&8» &cThe player is not online"

    give-usage: "&8» &cUsage: /phone give <player>"
    phone-given: "&8» &7You have given a phone to &e&n%player%"
    phone-received: "&8» &7You have received a phone from &e&n%player%"
    phone-number: "&8» &7Your phone number is &e&n%number%"

    number-usage: "&8» &cUsage: /phone number <player>"
    number-message: "&8» &7The phone number of &e&n%player%&7 is &e&n%number%"

    regen-usage: "&8» &cUsage: /phone regen <player>"
    phone-regenerated: "&8» &7You have regenerated the phone of &e&n%player%"

    renew-usage: "&8» &cUsage: /phone renew <player> <message>"
    invalid-number: "&8» &cInvalid phone number"
    phone-renewed: "&8» &7You have renewed the phone."

    whois-usage: "&8» &cUsage: /phone whois <number>"
    whois: "&8» &aThe phone number &e&n%number% &ais owned by &e%player%"

    repeater-given: "&8» &7You have received a repeater"
    repeater-usage: "&8» &cUsage: /phone repeater <speed> <range>"
    invalid-arguments: "&8» &cInvalid argument"

  conversations:
    player-add-name: "&8» &7Enter the name of the contact you want to add:"

    message-prompt: "&8» &7Send a message to the player:"
    player-not-online: "&8» &cThe player is not online"
    message-sent: "&8[&e%player% &7-> &aYou&8] &a%message%"
    message-sent-self: "&8[&aYou &7-> &e%player%&8] &a%message%"

    enter-number: "&8» &7Enter the phone number of the player:"
    number-not-found: "&8» &cThe phone number is not registered"
    contact-added: "&8» &7Contact added successfully."
    invalid-number: "&8» &cInvalid phone number"

  gui:
    error: "&cAn error occurred while loading your contacts"
    title: "&f七七七七七七七七ㇺ"

    accept-call: "Accept"
    no-pending-call: "&8» &cThere are no pending calls"
    call-accepted: "&8» &aYou have accepted the call"
    call-accepted-other: "&8» &a%player% has accepted the call"

    add-contact: "Add contact"

    next-page: "Next page &8(&e%page%&8/&e%max%&8)"
    previous-page: "Previous page &8(&e%page%&8/&e%max%&8)"

    deny: "Deny"
    close: "Close"

    deny-message: "&8» &cCall denied"
    close-message: "&8» &cYou have closed the call"

    phone-not-renewed: "&8» &cThe phone has not been renewed"
    phone-expired: "&8» &cThe phone has expired"
    no-signal: "&8» &cNo signal"
    no-messages: "&8» &cThere are no messages"
    player-not-found: "&8» &cThe player is not online"
    calling: "&8» &aCalling &e%player%"
    calling-other: "&8» &a%player% is calling you"

    signal:
      full: "&aFull Signal"
      half: "&eLow Signal"
      none: "&cNo Signal"

  listeners:
    no-phone-number: "&8» &cYou don't have a phone number"
    player-number: "&8» &7The phone number of &e&n%player%&7 is &e&n%number%"

    no-pending-call: "&8» &cThere are no pending calls"
    call-message: "&a%player% &8» &a%message%"
    call-message-self: "&aYou &8» &a%message%"

    no-signal: "&8» &cNo signal"