name: Phone
author: Michelo11
version: '${version}'
main: me.michelemanna.phone.PhonePlugin
api-version: '1.13'
softdepend:
    - PlaceholderAPI
commands:
    phone:
        description: Open the phone